twig:
    default_path: '%kernel.project_dir%/templates'
#    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        downloadsService: '@App\Service\DownloadService'
        mapperService: '@App\Service\MapperService'
        scoreService: '@App\Service\ScoreService'
        songService: '@App\Service\SongService'
        statisticService: '@App\Service\StatisticService'
    form_themes:
        - 'form/rating_type.html.twig'
        - '@TetranzSelect2Entity/Form/fields.html.twig'