#index:
#    path: /
#    controller: App\Controller\DefaultController::index
_errors:
  resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
  prefix:   /_error
#app.swagger_ui:
#  path: /api/doc
#  methods: GET
#  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }