name: Deploy Symfony Application

# Déclencher l'exécution du workflow sur un push dans la branche principale
on:
    push:
        branches:
            - master
            - beta

jobs:
    deploy-production:
        name: Deploy to Production
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master' # Exécuter uniquement pour les branches main/master

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Deploy via SSH
                uses: appleboy/ssh-action@v0.1.9
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USER }}
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    port: 22
                    script: |
                        cd /var/www/html/ragnacustoms.com/www
                        git pull origin master
                        composer install --no-dev --optimize-autoloader
                        php bin/console cache:clear --env=prod
                        php bin/console cache:warmup --env=prod
                        php bin/console doctrine:migrations:migrate --no-interaction
    deploy-beta:
        name: Deploy to Beta
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/beta' # Exécuter uniquement pour la branche beta

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v0.1.9
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: 22
                  script: |
                      cd /var/www/html/ragnacustoms.com/beta
                      git pull origin beta
                      composer update --no-dev --optimize-autoloader
                      php bin/console cache:clear --env=dev
                      php bin/console cache:warmup --env=dev
                      php bin/console doctrine:migrations:migrate --no-interaction
 
